version: '3.4'

services:
  am.devassessment:
    image: ${DOCKER_REGISTRY-}amdevassessment
    build:
      context: .
      dockerfile: AM.DevAssessment/Dockerfile
      args:
      - PASSWORD_ENV_SEEDED=SuperSecurePassword
    depends_on:
    - am.devassessment.api
  am.devassessment.api:
    image: ${DOCKER_REGISTRY-}amdevassessmentapi
    build:
      context: .
      dockerfile: AM.DevAssessment.Api/Dockerfile
      args:
      - PASSWORD_ENV_SEEDED=SuperSecurePassword
    depends_on:
    - mssqldata
  mssqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=DevassessmentPass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - mssql-volume:/var/opt/mssql
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P DevassessmentPass@word -Q 'SELECT 1' || exit 1"]
        interval: 60s
        retries: 3
        start_period: 10s
        timeout: 3s   
      
volumes:
  mssql-volume: